export const PlanetTypes = {
    barren: "Barren",
    ice: "Ice",
    arctic: "Arctic",
    snow: "Snow",
    tundra: "Tundra",
    boreal: "Boreal",
    lava: "Lava",
    ash: "Ash",
    arid: "Arid",
    desert: "Desert",
    mediterranian: "Mediterranian",
    jungle: "Jungle",
    toxic: "Toxic",
    steppes: "Steppes",
    savannah: "Savannah",
    monsoon: "Monsoon",
    atoll: "Atoll",
    terran: "Terrain",
    ocean: "Ocean",
    forest: "Forest",
    gasTemperate: "Gas Temperate",
    gasWarm: "Gas Warm",
    gasCold: "Gas Cold",
    gasFrozen: "Gas Frozen",
    gasHot: "Gas Hot",
    gasBurning: "Gas Burning",
}